server:
  port: 8002

spring:
  application:
    name: aoaojiao-cat-portal

  profiles:
    active: dev

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleteFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
