spring:
  datasource:
    url: jdbc:mysql://43.138.188.219:3306/crop-dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: yaCv9PDDrpr=
    driver-class-name: com.mysql.cj.jdbc.Driver
